[theme]
base = "dark"

backgroundColor = "#1e1e29"
secondaryBackgroundColor = "#2e303d"

textColor = "#f4f5f9"

primaryColor = "#0077fc"
linkColor = "#6bc4fe"

borderColor = "#4a5567"

headingFont = "Montserrat"
font = "Open Sans"

chartCategoricalColors = ["#6bc4fe", "#ffdf6f", "#ff7171"]

[[theme.fontFaces]]
family = "Montserrat"
url = "app/static/fontes/Montserrat.woff2"
weight = "400 700"
style = "normal"

[[theme.fontFaces]]
family = "Open Sans"
url = "app/static/fontes/OpenSans.woff2"
weight = "400 700"
style = "normal"

[server]
enableStaticServing = true
